### PR TITLE
Add PyPi support

### PR DESCRIPTION
**Pull request by BookOwl**

### CODE REVIEW

**Comment by PolyEdge** [comment]
How do I upload to PyPi?

**Comment by PolyEdge** [comment]
Merging, but I have some stuff to change.

**Comment by BookOwl** [comment]
I already uploaded it. Whenever you update things, I'll upload the changes to PyPi

**Comment by jeandrek** [comment]
> I already uploaded it. Whenever you update things, I'll upload the changes to PyPi

lolol
Where is it? I can't find any packages on PyPi

**Comment by BookOwl** [comment]
Here it is: https://pypi.python.org/pypi/scratchapi

**Comment by jeandrek** [comment]
cool so now can you just `pip install scratchapi`?

**Comment by BookOwl** [comment]
Yep! :) That's why I did this.

**Comment by PolyEdge** [comment]
Worked for me!

**Comment by jeandrek** [comment]
> https://github.com/notifications/beacon/AMk4vIcbYd1K7DVR1pERLggy8gjmbws2ks5pjjPOgaJpZM4HXX-W.gif

Empty picture? It's a web beacon :package:

**Pull request merged**
