### PR TITLE
Fix shebang

### PR DESCRIPTION
**Pull request by jeandrek**
Shebangs on *nix don't check the PATH environment variable and a full path to the executable needs to be specified.

### CODE REVIEW

**Comment by BookOwl** [comment]
He's using the Python Windows Launcher's shebang.

**Comment by jeandrek** [comment]
What's that?

**Comment by jeandrek** [comment]
Added executable bit to scratchapi.py

**Comment by jeandrek** [comment]
Does the Python Windows Launcher allow `#!/usr/bin/env python3`?

**Comment by PolyEdge** [comment]
idk i cant test atm

**Comment by BookOwl** [comment]
I think so.

**Comment by PolyEdge** [comment]
Yes, it works. I'll merge now.

**Comment by jeandrek** [comment]
Cool!

**Pull request merged**
